---
site_name: 'CustomMill MkDocs Theme'
site_description: 'Another iteration on the awesome Windmill theme for MkDocs'
site_author: 'Siphalor'
site_url: https://siphalor.github.io/mkdocs-custommill

repo_url: https://github.com/Siphalor/mkdocs-custommill

theme:
  name: null
  custom_dir: mkdocs_custommill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html, index.html, css/base.css]
  search_index_only: true
  include_search_page: true
  home: usage
  main_color: "#bb0000"
  gray: "#d0d0d0"
  lighter_gray: "#eeeeee"
  date_time_format: "%Y-%m-%d %H:%M:%S %Z"
  toc_depth: 2

nav:
  - Usage: usage.md
  - Customization: customization.md
  - Samples:
      - Sample Page A: sample-a.md
      - Sample Subfolder:
          - Sample Subpage A1: a/sample-a1.md
          - Sample Subpage A2: a/sample-a2.md
      - Sample Page B: sample-b.md

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - toc:
      permalink: '#'

plugins:
  - search
  - exclude:
      glob:
        - bootstrap/*
        - "*.scss"
      include-glob:
        - bootstrap/dist/js/bootstrap.js
        - bootstrap/dist/js/bootstrap.min.js        # For debugging
        - bootstrap/dist/js/bootstrap.min.js.map    # For debugging
        - bootstrap/dist/css/bootstrap.css
        - bootstrap/dist/css/bootstrap.min.css      # For debugging
        - bootstrap/dist/css/bootstrap.min.css.map  # For debugging

extra:
  history_buttons: false
  version: v1.3.0
  nav_links:
    - icon: twitter
      icon_type: brand
      text: Siphalor
      url: https://twitter.com/Siphalor
