site_name: 'CustomMill MkDocs Theme'
site_description: 'Another iteration on the awesome Windmill theme for MkDocs'
site_author: 'Siphalor'

repo_url: https://github.com/Siphalor/mkdocs-custommill

theme:
  name: null
  custom_dir: mkdocs_custommill
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates: [404.html, index.html, css/base.css]
  search_index_only: true
  include_search_page: true
  home: usage
  main_color: "#bb0000"
  gray: "#e0e0e0"
  lighter_gray: "#eeeeee"

nav:
- Usage: usage.md
- Customization: customization.md
- Samples:
  - Sample Page A: sample-a.md
  - Sample Subfolder:
    - Sample Subpage A1: a/sample-a1.md
    - Sample Subpage A2: a/sample-a2.md
  - Sample Page B: sample-b.md

markdown_extensions:
  - admonition
  - toc:
      permalink: '#'

extra:
  history_buttons: false
  version: v1.0.6
  nav_links:
  - icon: twitter
    text: Siphalor
    url: https://twitter.com/Siphalor
